# Generated by Django 4.1.5 on 2023-07-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.FileField(null=True, upload_to='locations'),
        ),
    ]
