# Generated by Django 4.1.5 on 2023-07-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='top_property',
            field=models.BooleanField(default=0),
        ),
    ]
