# Generated by Django 4.1.5 on 2023-08-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_rename_title_testimonial_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='top_property',
            new_name='is_featured',
        ),
    ]
