# Generated by Django 4.1.5 on 2023-05-02 14:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='picture',
        ),
        migrations.AddField(
            model_name='properties',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='highlight',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='slug',
            field=models.CharField(default='slug', max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='title',
            field=models.CharField(default='slug', max_length=100),
        ),
    ]
