# Generated by Django 4.1.5 on 2023-05-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_description'),
        ('properties', '0003_remove_properties_files_alter_properties_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='propertiesimage',
            name='images',
            field=models.FileField(null=True, upload_to='properties'),
        ),
    ]
