# Generated by Django 4.1.5 on 2023-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_properties_location_alter_propertiesimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
