# Generated by Django 4.1.5 on 2023-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_properties_lat_alter_properties_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='lat',
            field=models.DecimalField(decimal_places=30, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='lng',
            field=models.DecimalField(decimal_places=30, max_digits=40, null=True),
        ),
    ]
