# Generated by Django 4.1.5 on 2023-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_properties_lat_alter_properties_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
