# Generated by Django 4.1.5 on 2023-07-10 08:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_properties_lat_alter_properties_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='highlight',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
