# Generated by Django 4.1.5 on 2023-07-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertiesimage_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='lng',
        ),
    ]
