# Generated by Django 4.1.5 on 2023-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_properties_address_properties_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], default='for_sale', max_length=100),
        ),
    ]
