# Generated by Django 4.1.5 on 2023-07-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_properties_created_at_alter_properties_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='properties_images',
            field=models.ManyToManyField(to='properties.properties'),
        ),
        migrations.AlterField(
            model_name='propertiesimage',
            name='properties',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='properties_image', to='properties.properties'),
        ),
    ]
