# Generated by Django 4.1.5 on 2023-07-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_properties_properties_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='properties_images',
        ),
    ]
