# Generated by Django 4.1.5 on 2023-07-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_remove_properties_properties_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiesimage',
            name='properties',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.properties'),
        ),
    ]
