# Generated by Django 4.1.5 on 2023-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_propertiesimage_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], default='for_sale', max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('1', 'Apartment'), ('2', 'Vila'), ('3', 'Flat'), ('4', 'Rooms'), ('5', 'House')], default=1, max_length=100),
        ),
    ]
