# Generated by Django 4.1.5 on 2023-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_properties_status_alter_properties_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.IntegerField(choices=[('1', 'Apartment'), ('2', 'Vila'), ('3', 'Flat'), ('4', 'Rooms'), ('5', 'House')], default=1, max_length=100),
        ),
    ]
