# Generated by Django 4.1.5 on 2023-04-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
