# Generated by Django 4.1.5 on 2023-06-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Menu',
        ),
    ]
